# Task rewards percent
FOCUS_REWARDS_PERCENT = 0.025
AUDIO_REWARDS_PERCENT = 0.125

# Video length constants
MIN_VIDEO_LENGTH = 5  # five seconds
MAX_VIDEO_LENGTH = 120  # two minutes
FIVE_MINUTES = 300  # 5 minutes in seconds
TEN_MINUTES = 600  # 10 minutes in seconds
VALIDATOR_TIMEOUT = 90  # 1.5 minutes
VALIDATOR_TIMEOUT_MARGIN = 30  # 30 seconds

# Validator constants
CHECK_PROBABILITY = 0.1
DIFFERENCE_THRESHOLD = 0.1
SIMILARITY_THRESHOLD = 0.95
VIDEO_DOWNLOAD_TIMEOUT = 10
MIN_SCORE = 0.005
FAKE_VIDEO_PUNISHMENT = -5.0
QUERY_RELEVANCE_SCALING_FACTOR = 1.3
DESCRIPTION_RELEVANCE_SCALING_FACTOR = 0.7
VIDEO_RELEVANCE_WEIGHT = 0.65
FOCUS_MIN_SCORE = 0
MAX_FOCUS_SCORE = 1000
STUFFED_DESCRIPTION_PUNISHMENT = -5.0

# Description length scaling values.
DESCRIPTION_LENGTH_WEIGHT = 0.35
MIN_LENGTH_BOOST_TOKEN_COUNT = 100
MAX_LENGTH_BOOST_TOKEN_COUNT = 300


# Audio score constants
MIN_AUDIO_LENGTH_SECONDS = 45
MAX_AUDIO_LENGTH_SECONDS = 80
MIN_AUDIO_LENGTH_SCORE = 0.7
SPEAKER_DOMINANCE_SCALING_FACTOR = 0.5
BACKGROUND_NOISE_SCALING_FACTOR = 0.05
SPEECH_CONTENT_SCALING_FACTOR = 1.0 - BACKGROUND_NOISE_SCALING_FACTOR - SPEAKER_DOMINANCE_SCALING_FACTOR
AUDIO_LENGTH_SCALING_FACTOR = 0.25 # max 1
AUDIO_QUALITY_SCALING_FACTOR = 0.2 # max 1
DIARIZATION_SCALING_FACTOR = 0.4 # max 1
AUDIO_QUERY_RELEVANCE_SCALING_FACTOR = 1.0 - DIARIZATION_SCALING_FACTOR - AUDIO_LENGTH_SCALING_FACTOR - AUDIO_QUALITY_SCALING_FACTOR
