MIN_VIDEO_LENGTH = 5 # five seconds
MAX_VIDEO_LENGTH = 120  # two minutes
FIVE_MINUTES = 300  # 5 minutes in seconds
VALIDATOR_TIMEOUT = 90  # 1.5 minutes
VALIDATOR_TIMEOUT_MARGIN = 30  # 30 seconds

# Validator constants
CHECK_PROBABILITY = 0.1
DIFFERENCE_THRESHOLD = 0.05
SIMILARITY_THRESHOLD = 1 - DIFFERENCE_THRESHOLD
VIDEO_DOWNLOAD_TIMEOUT = 10
MIN_SCORE = 0.005
FAKE_VIDEO_PUNISHMENT = -5.0